In [33]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [53]:
x = np.array([1,2,3,4])
y = np.array([2,4,9,16])

In [54]:
model = LinearRegression()

x = x.reshape(-1, 1)
model.fit(x, y)

# if reshape not done then we get erroe : 
#ValueError: Expected 2D array, got 1D array instead: array=[1 2 3 4].
#Reshape your data either using array.reshape(-1, 1) if your data has a single feature or 
#array.reshape(1, -1) if it contains a single sample.

LinearRegression()

In [61]:
print("m = {},  b= {}   ".format(model.coef_, model.intercept_))

m = [4.7],  b= -4.0   


In [58]:
model.predict([[2]])

array([5.4])

####  SAVE MODEL
#####  two options- one with pickle.dump() and another with joblib.dump(). Later one is efficient when too many numpy structures are present

In [62]:
import pickle as p
with open('model_pickle_file', 'wb') as f:
    p.dump(model, f)

In [67]:
with open('model_pickle_file', 'rb') as f:
    mod = p.load(f)
mod.predict([[2]])

array([5.4])

In [70]:
#from sklearn.externals import joblib
import joblib
joblib.dump(model, 'model_file_joblib')

['model_file_joblib']

In [74]:
jm = joblib.load("model_file_joblib")

In [75]:
jm.predict([[2]])

array([5.4])