In [2]:
#Multiple Regression
#Credit goes to codebasics youtube
#Given  home prices CSV, find out price of a home that has:

#3000 sqr ft area, 3 bedrooms, 40 year old  AND
#2500 sqr ft area, 4 bedrooms, 5 year old

#  y = m1*f1 + m2*f2 + m3*f3 + b
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprice.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
# handle missing value
# here we take median of bedrooms column to fill NA
import math
median_bedrooms = math.floor(df.bedrooms.median())
print("median of bedrooms = ", median_bedrooms)
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

median of bedrooms =  4


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
#construct class object
reg_ob = linear_model.LinearRegression()

In [8]:
#syntax- fit(2D array of dependent variables,  1D array of dependent variable)
# that is same as fit(dataframe, series)

reg_ob.fit(df[['area', 'bedrooms', 'age']], df.price)
#[[]]  is required to have dataframe from anther datagrame

LinearRegression()

In [14]:
print("coeffients are", reg_ob.coef_)
print('interception b is ', reg_ob.intercept_)

coeffients are [  112.06244194 23388.88007794 -3231.71790863]
interception b is  221323.00186540425


In [11]:
#predict
reg_ob.predict([[2600, 3, 20]])

array([518217.63297611])

In [15]:
#cross verification
#y= m1*f1 + m2*f2 + m3*f3 + b
112.06244194*2600 + 23388.88007794*3 + -3231.71790863*20 + 221323.00186540425

518217.63297062425

In [12]:
reg_ob.predict([[3000,3,40]])

array([498408.25158031])

In [17]:
reg_ob.predict([[2500, 4, 5]])

array([578876.03748933])